#!groovy

// Generated by IBM TransformationAdvisor
// Mon Jan 28 03:34:18 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}